name: objectdb
description: Persistent embedded document-oriented NoSQL database for Dart and Flutter.
version: 1.0.8
author: Mario Reggiori <dev@marioreggiori.com>
homepage: https://github.com/marioreggiori/objectdb
environment:
    sdk: '>=2.0.0-dev.0.0 <3.0.0'

dependencies:
  execution_queue: ^1.0.2
  deeply: ^1.0.1

dev_dependencies:
  test: any
