name: objectdb
description: Persistent embedded document-oriented NoSQL database for Dart and Flutter.
version: 1.2.0-beta
homepage: https://github.com/marioreggiori/objectdb
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  execution_queue: ^1.2.0
  deeply: ^1.2.0+1
  objectid: 2.0.0-nullsafety.0

dev_dependencies:
  test: any
